!define INSTALL_MODE "both"

LangString welcomeSetup ${LANG_SIMPCHINESE} "欢迎使用 六壬占卜 安装向导"
LangString welcomeUnSetup ${LANG_SIMPCHINESE} "欢迎使用 六壬占卜 卸载向导"
LangString uninstallApp ${LANG_SIMPCHINESE} "正在卸载 六壬占卜..."
LangString sectionUninstall ${LANG_SIMPCHINESE} "卸载 六壬占卜"
LangString sectionApp ${LANG_SIMPCHINESE} "六壬占卜（必需）"
LangString sectionStartMenu ${LANG_SIMPCHINESE} "开始菜单快捷方式"
LangString sectionDesktop ${LANG_SIMPCHINESE} "桌面快捷方式"
LangString uninstallPrompt ${LANG_SIMPCHINESE} "确定要完全移除 六壬占卜 及其所有组件吗？"
LangString uninstallSuccess ${LANG_SIMPCHINESE} "六壬占卜 已成功从您的计算机移除。"
LangString installSuccess ${LANG_SIMPCHINESE} "六壬占卜 已成功安装。"
LangString installRunning ${LANG_SIMPCHINESE} "六壬占卜 正在运行，请先关闭后重试。"
LangString uninstallRunning ${LANG_SIMPCHINESE} "六壬占卜 正在运行，请先关闭后重试。"
LangString appDescription ${LANG_SIMPCHINESE} "六壬占卜 - 传统占卜工具"
LangString creatingShortcut ${LANG_SIMPCHINESE} "正在创建快捷方式..."
LangString closeApp ${LANG_SIMPCHINESE} "关闭应用程序"
LangString runAfterInstall ${LANG_SIMPCHINESE} "安装完成后运行 六壬占卜"
LangString currentInstallation ${LANG_SIMPCHINESE} "当前安装路径："
LangString selectInstallation ${LANG_SIMPCHINESE} "请选择安装路径"
LangString selectStartMenu ${LANG_SIMPCHINESE} "请选择开始菜单文件夹"
LangString installing ${LANG_SIMPCHINESE} "正在安装 六壬占卜..."
LangString extractingFiles ${LANG_SIMPCHINESE} "正在解压文件..."
LangString registering ${LANG_SIMPCHINESE} "正在注册应用程序..."
LangString completing ${LANG_SIMPCHINESE} "安装完成"
LangString cancelInstall ${LANG_SIMPCHINESE} "确定要取消安装吗？"
LangString cancelUninstall ${LANG_SIMPCHINESE} "确定要取消卸载吗？"
