!define PRODUCT_NAME "六壬占卜"
!define PRODUCT_VERSION "${PRODUCT_VERSION}"
!define INSTALL_MODE "both"

LangString welcomeSetup ${LANG_SIMPCHINESE} "欢迎使用 ${PRODUCT_NAME} 安装向导"
LangString welcomeUnSetup ${LANG_SIMPCHINESE} "欢迎使用 ${PRODUCT_NAME} 卸载向导"
LangString uninstallApp ${LANG_SIMPCHINESE} "正在卸载 ${PRODUCT_NAME}..."
LangString sectionUninstall ${LANG_SIMPCHINESE} "卸载 ${PRODUCT_NAME}"
LangString sectionApp ${LANG_SIMPCHINESE} "${PRODUCT_NAME}（必需）"
LangString sectionStartMenu ${LANG_SIMPCHINESE} "开始菜单快捷方式"
LangString sectionDesktop ${LANG_SIMPCHINESE} "桌面快捷方式"
LangString uninstallPrompt ${LANG_SIMPCHINESE} "确定要完全移除 ${PRODUCT_NAME} 及其所有组件吗？"
LangString uninstallSuccess ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 已成功从您的计算机移除。"
LangString installSuccess ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 已成功安装。"
LangString installRunning ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 正在运行，请先关闭后重试。"
LangString uninstallRunning ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 正在运行，请先关闭后重试。"
LangString appDescription ${LANG_SIMPCHINESE} "${PRODUCT_NAME} - 传统占卜工具"
LangString creatingShortcut ${LANG_SIMPCHINESE} "正在创建快捷方式..."
LangString closeApp ${LANG_SIMPCHINESE} "关闭应用程序"
LangString runAfterInstall ${LANG_SIMPCHINESE} "安装完成后运行 ${PRODUCT_NAME}"
LangString currentInstallation ${LANG_SIMPCHINESE} "当前安装路径："
LangString selectInstallation ${LANG_SIMPCHINESE} "请选择安装路径"
LangString selectStartMenu ${LANG_SIMPCHINESE} "请选择开始菜单文件夹"
LangString installing ${LANG_SIMPCHINESE} "正在安装 ${PRODUCT_NAME}..."
LangString extractingFiles ${LANG_SIMPCHINESE} "正在解压文件..."
LangString registering ${LANG_SIMPCHINESE} "正在注册应用程序..."
LangString completing ${LANG_SIMPCHINESE} "安装完成"
LangString cancelInstall ${LANG_SIMPCHINESE} "确定要取消安装吗？"
LangString cancelUninstall ${LANG_SIMPCHINESE} "确定要取消卸载吗？"

!insertmacro MUI_LANGUAGEFILE_BEGIN SIMPCHINESE

!ifndef MUI_PRODUCTNAME
  !define MUI_PRODUCTNAME "${PRODUCT_NAME}"
!endif

!ifdef MUI_UNINSTALLER
  !define MUI_PAGEHEADER_TEXT "${PRODUCT_NAME} 卸载向导"
  !define MUI_PAGEHEADER_SUBTEXT "从您的电脑中移除 ${PRODUCT_NAME}"
  !define MUI_INSTFILESPAGE_TITLE "卸载 ${PRODUCT_NAME}"
  !define MUI_INSTFILESPAGE_SUBTITLE "正在卸载 ${PRODUCT_NAME}"
  !define MUI_FINISHPAGE_TITLE "卸载完成"
  !define MUI_FINISHPAGE_TEXT "${PRODUCT_NAME} 已成功从您的电脑中移除。\r\n\r\n点击「完成」关闭此向导。"
  !define MUI_FINISHPAGE_BUTTON "完成(&F)"
  !define MUI_TEXT_ABORTWARNING "您确定要退出 ${PRODUCT_NAME} 的安装吗？"
  !define MUI_UNTEXT_CONFIRMUNINSTALL_SUBTITLE "从以下位置移除：\n$INSTDIR"
  !define MUI_UNTEXT_UNINSTALLING_TITLE "正在卸载"
  !define MUI_UNTEXT_UNINSTALLING_SUBTITLE "请等待，${PRODUCT_NAME} 正在被卸载。"
!else
  !define MUI_PAGEHEADER_TEXT "${PRODUCT_NAME} 安装向导"
  !define MUI_PAGEHEADER_SUBTEXT "将在您的电脑上安装 ${PRODUCT_NAME}"
  !define MUI_DIRECTORYPAGE_TEXT "安装程序将把 ${PRODUCT_NAME} 安装到以下文件夹。$\n$\n如需安装到其他目录，请点击「浏览」并选择其他路径。"
  !define MUI_DIRECTORYPAGE_SUBTITLE "选择安装路径"
  !define MUI_DIRECTORYPAGE_BROWSETEXT "浏览(&B)..."
  !define MUI_INSTFILESPAGE_TITLE "正在安装"
  !define MUI_INSTFILESPAGE_SUBTITLE "请等待，${PRODUCT_NAME} 正在安装中..."
  !define MUI_FINISHPAGE_TITLE "安装完成"
  !define MUI_FINISHPAGE_TEXT "${PRODUCT_NAME} 已成功安装到您的电脑中。\r\n\r\n勾选下方选项后点击「完成」。"
  !define MUI_FINISHPAGE_RUN "运行 ${PRODUCT_NAME}(&R)"
  !define MUI_FINISHPAGE_SHOWREADME "查看发行说明(&V)"
  !define MUI_FINISHPAGE_BUTTON "完成(&F)"
  !define MUI_TEXT_ABORTWARNING "您确定要取消 ${PRODUCT_NAME} 的安装吗？"
  !define MUI_TEXT_LICENSE_TITLE "许可协议"
  !define MUI_TEXT_LICENSE_SUBTITLE "请阅读 ${PRODUCT_NAME} 的许可协议条款"
  !define MUI_TEXT_COMPONENTS_TITLE "组件选择"
  !define MUI_TEXT_COMPONENTS_SUBTITLE "选择您想要安装的组件功能。"
  !define MUI_TEXT_STARTMENU_TITLE "选择开始菜单文件夹"
  !define MUI_TEXT_STARTMENU_SUBTITLE "选择创建快捷方式的开始菜单文件夹"
  !define MUI_TEXT_INSTALLING_TITLE "正在安装"
  !define MUI_TEXT_INSTALLING_SUBTITLE "请等待，${PRODUCT_NAME} 正在安装中..."
  !define MUI_TEXT_FINISH_TITLE "安装完成"
  !define MUI_TEXT_FINISH_SUBTITLE "安装已成功完成"
  !define MUI_TEXT_RUN & "&运行 ${PRODUCT_NAME}"
  !define MUI_TEXT_SHOWDETAILS "显示详细信息(&D)"
  !define MUI_TEXT_AGREETOCONTINUE "我同意(&A)"
  !define MUI_I_NEXTPAGE & "下一步(&N) >"
  !define MUI_I_BACK "< 上一步(&B)"
  !define MUI_I_CANCEL "取消"
  !define MUI_I_CLOSE "关闭"
  !define MUI_BUTTONTEXT_FINISH "完成(&F)"
!endif

!insertmacro MUI_LANGUAGEFILE_END
